export const REDIS_CLIENT_TOKEN = 'REDIS_CLIENT' as const;
export const REDIS_PUBLISHER_TOKEN = 'REDIS_PUBLISHER' as const;
export const REDIS_SUBSCRIBER_TOKEN = 'REDIS_SUBSCRIBER' as const;
export const DEFAULT_REDIS_CONNECT_TIMEOUT_MILLISECONDS = 5000 as const;
export const REDIS_RECONNECT_DELAY_INCREMENT_MILLISECONDS = 50 as const;
export const REDIS_RECONNECT_DELAY_MAX_MILLISECONDS = 2000 as const;
